//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monets.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monets.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format. Prvo slovo mora biti veliko, minimalno 3 i maximalno 20 karaktera..
        /// </summary>
        internal static string ImePrezimeNeispravanFormat {
            get {
                return ResourceManager.GetString("ImePrezimeNeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 4 karaktera..
        /// </summary>
        internal static string MinimalnaDuzina {
            get {
                return ResourceManager.GetString("MinimalnaDuzina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format nije ispravan!.
        /// </summary>
        internal static string NeispravanFormat {
            get {
                return ResourceManager.GetString("NeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate odabrati barem jednu ulogu!.
        /// </summary>
        internal static string NeispravanOdabirUloge {
            get {
                return ResourceManager.GetString("NeispravanOdabirUloge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format telefona. Ispravn primjer: 060-000-000 ili 060/000/0000 ili 0621234567.
        /// </summary>
        internal static string NeispravanTelefon {
            get {
                return ResourceManager.GetString("NeispravanTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovo polje je obavezno!.
        /// </summary>
        internal static string ObaveznoPolje {
            get {
                return ResourceManager.GetString("ObaveznoPolje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke nisu iste!.
        /// </summary>
        internal static string RazliciteLozinke {
            get {
                return ResourceManager.GetString("RazliciteLozinke", resourceCulture);
            }
        }
    }
}
